export { InlineDashboardRegio } from './dashboards/deprecated/index'
export { InlineDashboardRegioSamenvatting } from './dashboards/regio-samenvatting/index'
export { InlineDashboardRegioInstroom } from './dashboards/regio-instroom/index'
export { InlineDashboardRegioDiplomering } from './dashboards/regio-diplomering/index'
export { InlineDashboardRegioArbeidsmarkt } from './dashboards/regio-arbeidsmarkt/index'
