apiVersion: v1
kind: Service
metadata:
  name: {{ include "onderwijsdata-chat.fullname" . }}
  labels:
    {{- include "onderwijsdata-chat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "onderwijsdata-chat.selectorLabels" . | nindent 4 }}
