apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - helmrepo.yaml
  - secret.yaml
  - middleware.yaml

configMapGenerator:
  - name: development-config
    files:
      - values.yaml=values.yaml

configurations:
  - ../base/kustomizeconfig.yaml
