apiVersion: v1
kind: Secret
metadata:
    name: onderwijsdata-chat-secrets
type: Opaque
stringData:
    AZURE_AI_API_KEY: ENC[AES256_GCM,data:vyFf7/Eu7a9CVd5kdPkjZ48vLLavjB+HlOtwXm3Ob+juPXH8TpPSy2pCeHl4qFOAy59DbMwRtAaEn/Khq43q7KBgzTOS5C+3xRnozHaY5VcgkBYy,iv:IXZxe7X/0glHuH9ycmxQORD8yE1RDGItMzPhOqu9Fw8=,tag:We1RcToDxACvg5/qlCulRw==,type:str]
    AZURE_AI_API_BASE: ENC[AES256_GCM,data:GZbX3fyriIftYWC6Skxle7ImzEhB35kSfswzXopZjYO0jOBpSZ35oNCgzl6FpP0faXkEkgpcwIjJ+2cGXcPMQzkDtvF/Sf7GKgmTlnxn,iv:lZKdUdRW5cxx/OmzYHZ3VzMnRxrjooWdiAo7Ss6yBDk=,tag:ibJNQ45e7/LDLPfNYy2stA==,type:str]
    CHAT_SECRET: ENC[AES256_GCM,data:K1l1ouc0lE1RhAWHyi+z2BopcDVuXCzXWRJbdTMBFmr8ziZV36QaW5S1mhNmOD0/amJaq9zY48R0H4q1kP4yhg==,iv:PsoY6l8UaM8xer5LxXkfiDx9slBob+oMoqPUWxO0H2k=,tag:2ak2bhXKI2nyYfvEc7UG6Q==,type:str]
    CHAT_USERS: ENC[AES256_GCM,data:2TF1deNDT5GFgJdz+6QkNtHPAm+YczHv7n6CGquZj38k0Q/YLv5ql9+jKjMZP5Sz,iv:SUwLheuI+KmWD0xBB0UY57WM3qc6P4hzCRvk/ubVsSk=,tag:35aqaDNbBzljI+AUkRqXlQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Ma/L+DBzw2UqTV2lh3rMtCbQ85S2gyG3UTPbxI0JpixaXD7zP0YK9A==,iv:dZD/RK3/up3fahnawdILt1uKan6fktkSTaHwGgNHCYA=,tag:C23OoYGhGnQvSI/aPZADBw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:qQsP+vJSmHTtZwT00QII18a6ZXddm2nMWTAZi31HiGndAoVgavBjGOQudtJ27B6aDTzYmF9LthyJydlDf2h5lA==,iv:fL758b+Uj9ht5esKIQkoP+UT34Yf+JnhMFkdAs4qb8k=,tag:BKQhkxQBV4FwW6m6lGxlJQ==,type:str]
    WILLMA_API_KEY: ENC[AES256_GCM,data:ql/rOwwU44r45UCiCaYzvPm5QHSbXScTUZZ8hk8UhYxPWSW8byi0kxQ4T+NN7RvHnw==,iv:I6r5sYtsYpeKnLPtaaMhIQEu9q40RcKkJyq+duWHSbI=,tag:tg8tsXCg3u8No5q7xPsiyQ==,type:str]
sops:
    age:
        - recipient: age13ejdywvccrp79fxcsgk7ggk8k8n3vrwdked3djzku4javrg3wfzszsf55q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Wm9ZeXVHaFlGaWVacllr
            Z0RqaGFSeVhwbGdKZWpFWDNreXFPcUlNN0hVCmZnWndVWXJPcUJNUlBaOTNFS012
            eURkYVNHVC9FeDFrWU12YnRtaWc2cG8KLS0tIHVOSy9TL2h0dzlJdnpTTjJ4YXpa
            TzZ3QVhFU3h0dk5kYXJoVVFadW1taEUK68lfPPuc9iBM5KtCw/J97ocP6hBvKDYW
            jUV9d/OP89991XsDNSwgm/pHyBM0NSseZFF4QcK3UPY/GZsgkPOyiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T11:07:57Z"
    mac: ENC[AES256_GCM,data:sK8cETqozzZvQQ5GvGsTJhVjHK4T/QppkFwMt9WDbje7EGX5UJuSjq/qus5W7Ys4fQhZa1tAtrSLyTmDCrPRJtQD7AvLbMimzXN6poomb+dSwueEo45DZ7RezYGC1AAuTC6u6nNRGy31WGajSpXbdRqlFcyEdpFGKL8SHehW4l8=,iv:/PwddFQ2Vhr5tLp8ieldTenhqsBTxF4IMirHwDGNLVU=,tag:sNYV3Qwf4WlbBSOWBOBx8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
