// A report only makes sense once data was actually fetched or plotted;
// greetings, definitions and clarification questions don't qualify.
export function hasReportableAnswer(messages) {
  return messages.some(m =>
    m.role === 'assistant' && !m.isError &&
    (m.figures?.length > 0 || m.tools?.some(t => t.snippet))
  )
}

// Reports are generated by the backend from the datasets loaded in the
// current session (its `data_keys`). A reopened conversation restores only
// message text, not those keys, so history figures must not enable the
// button: the user has to ask a question again to re-load the data.
export function canGenerateReport(liveMessages, restoredMessages = []) {
  if (hasReportableAnswer(liveMessages)) return 'ready'
  if (hasReportableAnswer(restoredMessages)) return 'needs_reload'
  return 'no_data'
}
