// A report only makes sense once data was actually fetched or plotted;
// greetings, definitions and clarification questions don't qualify.
export function hasReportableAnswer(messages) {
  return messages.some(m =>
    m.role === 'assistant' && !m.isError &&
    (m.figures?.length > 0 || m.tools?.some(t => t.snippet))
  )
}

// Reports are generated by the backend from the datasets loaded in the
// current session (its `data_keys`). A reopened conversation gets those keys
// back only for tables whose recipe the server saved (#472): it says how many.
// Without them, history figures must not enable the button: the user has to
// ask a question again to re-load the data.
export function canGenerateReport(liveMessages, restoredMessages = [], restoredDataKeys = 0) {
  if (hasReportableAnswer(liveMessages)) return 'ready'
  if (hasReportableAnswer(restoredMessages)) return restoredDataKeys > 0 ? 'ready' : 'needs_reload'
  return 'no_data'
}
