apiVersion: v1
kind: Secret
metadata:
    name: onderwijsdata-chat-secrets
type: Opaque
stringData:
    AZURE_AI_API_KEY: ENC[AES256_GCM,data:IFDggLhV09pyFTjY2H4yHBRYqLsOkuwXnPq7Vr6FlQueWC/u2fAFopa7GfPo2L0y4Rs4Mxxd5BNVXZix1FQR7Jb4PW6dPMj9zE2L0NMBv2CblFXN,iv:d6Xm7R3vlGhMIH+L/GgAMLH++K9XKDG2ETeK5JEFRGw=,tag:rLAkgY6E4GmdUBui5Nk6vA==,type:str]
    AZURE_AI_API_BASE: ENC[AES256_GCM,data:XoKWyaxtn/SJ7pWgXRPgf2uo9CzWRb0QSNC9kktb8MZUBpt0/Est2Lc3+ZYTWnNH12dbPIhgEh9L0XK/HaVaYI5BE0q5rAmL4/N2B409,iv:Ps+pneC0x9tVskriG6i0ent9CXrGq2t6GCd5yEDdAyw=,tag:q6gJ74NjsbyjziJY8QSJsw==,type:str]
    CHAT_SECRET: ENC[AES256_GCM,data:W0kGzUMaXnK/ih23Q/0QDxGmm+ObhgzLp1AF2oxa6PauojH1caMiht+8narUcXDwXQRqmqhT55tgX2Y8Kwb5TQ==,iv:iaI6v9USVVGrnAoCQtpYmqZK/2t8fhFLcxjoFkLHYrY=,tag:NBWCUA0c8IbNQkVYFQVmwA==,type:str]
    CHAT_USERS: ENC[AES256_GCM,data:k5kXoyoqmgqUIDu0L/EQTyS7FD5hUmlAomQWmpif5RI6eGPsqQYyFW8KZArSwFKF,iv:EbYSxCs6NDbzZwGw4OserxhKbXpzFJwKeqD+V4fCzpo=,tag:vqjrmkSIB5qRFne3qZG/TQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:7uNtQtKpau24KSzDxJEjE6w7oIIHZCYFo/JEwnnTUnifY+kYxxQn9Q==,iv:3FgtTzADkExNjvDSrQzXSu8L6hnsKZg30HHHQ7R46NQ=,tag:WLwvq/G0dj2E3a5f5nZwnw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:c5PdsaWkwxgc97jvDD11VJy6dMJEdz8J/r2KO8TpA65qd7DiBO681uMP93XnhrsGFLoY4GdXwSoyY4TEV4Zbng==,iv:14H1BTsCNE8UkFogMEE1wOVYYz3M7Gymed0p1Im5yZ4=,tag:mabLi+7BN1hAnFyJImwtMg==,type:str]
    WILLMA_API_KEY: ENC[AES256_GCM,data:73jqHppA6LxYC88mxvqZZkRIe0jk9bD1Sygy8kFZopiApzlz2n9sUiahMyyke7GLTA==,iv:AASaCtAvsONPQwBV2TH375za+R9jycVXUS8tcc0kknk=,tag:47rf8mzwLvhjBbR+0mjpoA==,type:str]
sops:
    age:
        - recipient: age13ejdywvccrp79fxcsgk7ggk8k8n3vrwdked3djzku4javrg3wfzszsf55q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MGk0WDVjR2ZmMGJZQ0RF
            OHVCb0FYUVRJRGU4Y1c0R09LamluVnZ1UVZzCm8yLyswS2lhSTBTeEkrQ25aWDF2
            U3ljK1Y3Q2VmTEdhYVJFNXdRdW1qaU0KLS0tIEJUNTJYZUJ5K2d1SjFaeGRJWkVm
            bXp1ZnNrbnQrbU1lUjBiQlpTOXpFVGcKW7BFYbPqE1xI4pXPVQv9nizaRl5Kk48n
            zwBrTuTLvCYq4Z2jjTwRLAOgQPEqTJUATXb3+i/Sc3jeaSCR+x27BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T15:38:39Z"
    mac: ENC[AES256_GCM,data:sDTaoHwv2wjiwmxzNr6XqXL7oA4pqOdjPAQws34KCsfgAaMLUhxRuPu5su/awRWsxBCaTPgUOaLntspzGEvnpdVUdpTjds95vJee6Q4d489f/DP8Hxdr9dgPPXBmK/nwyESMiydX8SWw6MCI8quEBrCeOs1MrAKkvs3j23FbGyw=,iv:tnmx4m+QwAnWstPyQnzoMimR5U/yE7UibOksa/JG+Eg=,tag:224/Z/r400uKQUmhInJhYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
