apiVersion: v1
kind: Secret
metadata:
    name: onderwijsdata-chat-secrets
type: Opaque
stringData:
    AZURE_AI_API_KEY: ENC[AES256_GCM,data:oSIhVU1Nys0M/gwY0oxTNJW+xvVX5Jpc1HV5HpylIVhNr/ZosKEkZA8cxbbOcsSIZViRzDvlPSenyY0687wTt66aCZHctyuW8rVcYTFtk1tQjYYagw==,iv:2MYLr3byjGhW3I/amcQp94ilIQIFz4+wDfBZOhBUDsc=,tag:u2KHCwwff3Ep2BhLa+2Fjg==,type:str]
    AZURE_AI_API_BASE: ENC[AES256_GCM,data:vB4Mcsh8EJRuc3kiA+9+2oP5QDhgKM0nE8cYfPX9HP9kW+ub2rH24fv5hjHCsvFMO55l8FauxmwOhMaRgO0p24uOorbIdK/hq101xxpB,iv:3PZx5cAKx0jGDP5CY3GLcIPV39eQu6+J0WZqtt62wzE=,tag:yQOFcuTuHqqaN8VcyHHXsw==,type:str]
    CHAT_SECRET: ENC[AES256_GCM,data:sd53I9M5zdGJ/hDm6oFejbhWHJFtAE0twJYcPBZDTithXIZx6rrwKa1nDOUuzEL07U2ZRQdqlD4Rq1tI8hgx0Q==,iv:4mfXksn1yGSredJrti/wPg+v66erd98PPvnakYrnSG8=,tag:ZSJRP3NfaqPyebR1NNZPZw==,type:str]
    CHAT_USERS: ENC[AES256_GCM,data:KxG2opdBF+fms3IzQl9SgkCV+6UAPKMERcYjNcEvFvkpTB1W8AvILNxb/6iOIeWD,iv:NKPRSXMUdIZwXiin+ToQP7LqxzW8yFolYngBGF+0CvU=,tag:b/vM74IkNw+fDcvDOLbrCA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:3mIRzUCCVb4Ab4bLF2ezHik0bI59tBNAe6TXFqdz6jwib3KWqmua7g==,iv:NpTqgH89MNaGiXLkMVaE7qUAgK2amYZh/9/wb5U5X3g=,tag:1JeXJ9+rbc0b89ZoeczItg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ek1Ft9jOqMSdoJeJWbUGYomgfro3KyJEm0PNsZK1LZuaTO3YrNMXQZBSITHSRrVQ5+mofPzKMPd2+nCcZ1kcMQ==,iv:2ub5ypLQFBpBDtvV0cS8DY4pJELmulmNADtGuyS+0E8=,tag:F++3w50nKifTT1xi/Rl7fA==,type:str]
    WILLMA_API_KEY: ENC[AES256_GCM,data:6yicylaMLxIX8UuzuU+mS93+nLemw+0c+n/bnXoxluhSUi4aCUdy1sucwCL7n1vufg==,iv:een9H/AyPf/Fyg+s6FaG2yVq4FctrSNwJ/+5kOr85W0=,tag:PNTKQqz6PHD4TPq5BgoEcQ==,type:str]
sops:
    age:
        - recipient: age13ejdywvccrp79fxcsgk7ggk8k8n3vrwdked3djzku4javrg3wfzszsf55q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU0RPUnhzNGU2T1R4UUwz
            d2hKQVQ2M1pZOXYwTGl3bC9aWEhHdlNhL1JVCjh6SHF0eUdEcjVTWUNnd3hjeVFP
            TmdNalpiYkoxTlJBZVJ0eGdvTEdrTEEKLS0tIENITmV1ZGFPcHF2TzdEdm10eTlM
            L2w3Tm9IamJJQTVpU1RNbXRTQzM3MEkKqrxY4L5XXUxgJxjphHghdiXZAP4peVJC
            NZrtYB8L39gr3OOH6cvWNcpDyquxY5IXy67zD4Now/ywuZPe4dASgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T11:07:57Z"
    mac: ENC[AES256_GCM,data:b7TfnQG/+wQn6h3n5sl8FN3dtmHwBuW/eSY5zyKVc7A/tUBVuyHkbll4/OAJeBQ7hqHkiz8OsGB3zEhlhZy5d4QVyN0ZWhCHJ8T4c/HntQlqspaGpHZ5EVTSW541j5RpxPF0QZypzBO2a+vsktDzvasrzIZdxmkfloSBZj9K4ic=,iv:HEgBy/su51ynWJT5QLeVKwo+CQDMaWvHvN7vufFjlpM=,tag:Qj//OirkRm8JYyc7g56Zdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
